### ISSUE TITLE
Cannot compile using Vesyla new version

### ISSUE THREAD

**Issue by his4000** [silagokth/vesyla-1#11]
**Describe the bug**

After I update the new version of Vesyla you pushed 2019. 04. 03., I cannot compile simple loop statements like below:

~~~matlab
dimarch = [1:1024]  %! MEM[0, 0]
rf = zeros(1, 64);  %! RFILE[0, 0]

for i = 1:16
    rf = dimarch((i-1)*64+1:i*64);
end
~~~

**To Reproduce**
Make matlab file includes the code above and compile using new version of Vesyla.

**Expected behavior**
Compile success

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/22610518/55537957-41f58b80-56f8-11e9-936c-f69f4363cac9.png)

**Comment by herenvarno** [comment]
check your config/hardware_def.xml, make sure your register file depth is 64

**Comment by herenvarno** [comment]
fixed, please pull the new code
